### ISSUE TITLE
Problem with secp256k1

### ISSUE THREAD

**Issue by bilthon** [node-lightning/node-lightning#334]
I'm using just the `@node-lightning/invoice` package in a project, importing version `0.28.0`. The problem happens when I try to run a unit test and is the following:

```

Loading jest.config.js...
 FAIL  src/account/account.service.spec.ts
  ● Test suite failed to run

    Cannot find module '/Users/bilthon/Development/NestJS/Projects/backend/node_modules/@node-lightning/secp256k1/build/Release/addon' from '../node_modules/@node-lightning/secp256k1/dist/index.js'

    Require stack:
      /Users/bilthon/Development/NestJS/Projects/backend/node_modules/@node-lightning/secp256k1/dist/index.js
      /Users/bilthon/Development/NestJS/Projects/backend/node_modules/@node-lightning/crypto/dist/key.js
      /Users/bilthon/Development/NestJS/Projects/backend/node_modules/@node-lightning/crypto/dist/index.js
      /Users/bilthon/Development/NestJS/Projects/backend/node_modules/@node-lightning/invoice/dist/crypto.js
      /Users/bilthon/Development/NestJS/Projects/backend/node_modules/@node-lightning/invoice/dist/decoder.js
      /Users/bilthon/Development/NestJS/Projects/backend/node_modules/@node-lightning/invoice/dist/index.js
      lndhub/lndhub.service.ts
      account/account.service.ts
      account/account.service.spec.ts

      at Resolver._throwModNotFoundError (../node_modules/jest-resolve/build/resolver.js:491:11)
      at Object.<anonymous> (../node_modules/@node-lightning/secp256k1/lib/index.ts:14:15)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.034 s, estimated 5 s
```

When looking at the referenced files, I check the contents of `../node_modules/@node-lightning/secp256k1/dist/index.js` and can see this:

```=
"use strict";
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-var-requires */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !exports.hasOwnProperty(p)) __createBinding(exports, m, p);
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
__exportStar(require("./EcdhOptions"), exports);
__exportStar(require("./EcdsaOptions"), exports);
__exportStar(require("./EcdsaResult"), exports);
__exportStar(require("./Secp256k1"), exports);
const path_1 = __importDefault(require("path"));
const Secp256k1_1 = require("./Secp256k1");
const addon = require(path_1.default.resolve(__dirname, "../build/Release/addon"));
const instance = new Secp256k1_1.Secp256k1(new addon.Secp256k1());
exports.default = instance;
//# sourceMappingURL=index.js.map
``` 

Then, looking at the referenced file `../build/Release/addon`, I can confirm that a very similar file does exist inside `node_modules` at the specified location, the only difference being that it's called `addon.node` instead of just `addon`. And surely enough if I just manually edit the generated `index.js` to reference to `addon.node` things work!

I'd normally submit a PR for this, but I'm not sure if this is a platform-specific issue (I'm running this on a mac M1 by the way) so I'm opening this issue first. I also honestly don't know what this part of the code does, I just made it work by fiddling with it 😄

**Comment by lescuer97** [comment]
I'm running on linux with pnpm and having the same problem

**Comment by bmancini55** [comment]
Thanks for reporting the issue.  What version of NodeJS are you both using? 

In the NodeJS docs`require` should find files with `.node` extension.  It can't hurt to make it more explicit and directly load `addon.node` instead of `addon`.

**Comment by lescuer97** [comment]
> Thanks for reporting the issue. What version of NodeJS are you both using?
> 
> In the NodeJS docs`require` should find files with `.node` extension. It can't hurt to make it more explicit and directly load `addon.node` instead of `addon`.

turns out my  problem has something to do with not being able to being used in the browser. 
I was using sveltekit. when I import on the side of the server everything works great it's only on the browser side that the problem happens
